spring:
  application:
    name: authenticatorApp
  h2:
    console:
      enabled: true
      path: /console/
  datasource:
    url : jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE   
      
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: update
        
  security:
    oauth2:
      client:
        registration:
         google:
          clientId: ${clientId}
          clientSecret: ${clientSecret}
          scope:
           - email
           - profile            
